package wtf.qase.power_optimization_survivor.dto

enum class PowerManagerSetting {
    XIAOMI_AUTOSTART,
    XIAOMI_BATTERY_SAVER,
    HUAWEI_LOCK_SCREEN_CLEANUP,
    HUAWEI_APP_LAUNCH,
    OPPO_POWERMANAGET,
    OPPO_STARTUPMANAGER,
    ASUS_MOBILE_MANAGER,
    ASUS_AUTOSTART,
    SAMSUNG_BATTERY
}
